
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINAWARD BEGINFINALS BEGINGROUPA BEGINGROUPB BEGINGROUPC BEGINGROUPD BEGINGROUPE BEGINGROUPF BEGINGROUPG BEGINGROUPH BEGINKNOCKOUT BEGINQF BEGINROF16 BEGINSF BEGINTABLE BEGINTEAMNAME BEGINTPPO CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSELI CLOSEROW CLOSESPAN CLOSESTYLE CLOSESUP CLOSETABLE CLOSETIME CODEDCHAR CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENLI OPENROW OPENSPAN OPENSTYLE OPENSUP OPENTABLE OPENTIMEstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | OPENSUP skiptag\n               | CLOSESUP skiptag\n               | handleli : OPENLI OPENHREF CONTENT CLOSEHREF skiptag CLOSELI skiptag handleli\n                | OPENLI CONTENT CLOSELI handleli\n                |handleData : OPENDATA skiptag handleli CLOSEDATA handleData\n                  |handlerow : OPENROW handleData CLOSEROWtable : BEGINTEAMNAME skiptag OPENTABLE handlerow CLOSETABLE'
    
_lr_action_items = {'BEGINTEAMNAME':([0,],[3,]),'$end':([1,2,18,],[0,-1,-14,]),'CONTENT':([3,5,6,7,8,9,20,24,26,31,34,],[5,5,5,5,5,5,5,27,29,5,5,]),'OPENHREF':([3,5,6,7,8,9,20,24,31,34,],[6,6,6,6,6,6,6,26,6,6,]),'CLOSEHREF':([3,5,6,7,8,9,20,29,31,34,],[7,7,7,7,7,7,7,31,7,7,]),'OPENSUP':([3,5,6,7,8,9,20,31,34,],[8,8,8,8,8,8,8,8,8,]),'CLOSESUP':([3,5,6,7,8,9,20,31,34,],[9,9,9,9,9,9,9,9,9,]),'OPENTABLE':([3,4,5,6,7,8,9,11,12,13,14,15,],[-7,10,-7,-7,-7,-7,-7,-2,-3,-4,-5,-6,]),'OPENLI':([5,6,7,8,9,11,12,13,14,15,20,22,30,34,35,],[-7,-7,-7,-7,-7,-2,-3,-4,-5,-6,-7,24,24,-7,24,]),'CLOSEDATA':([5,6,7,8,9,11,12,13,14,15,20,22,23,30,32,34,35,36,],[-7,-7,-7,-7,-7,-2,-3,-4,-5,-6,-7,-10,25,-10,-9,-7,-10,-8,]),'CLOSELI':([5,6,7,8,9,11,12,13,14,15,27,31,33,],[-7,-7,-7,-7,-7,-2,-3,-4,-5,-6,30,-7,34,]),'OPENROW':([10,],[17,]),'CLOSETABLE':([16,21,],[18,-13,]),'OPENDATA':([17,25,],[20,20,]),'CLOSEROW':([17,19,25,28,],[-12,21,-12,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,8,9,20,31,34,],[4,11,12,13,14,15,22,33,35,]),'handlerow':([10,],[16,]),'handleData':([17,25,],[19,28,]),'handleli':([22,30,35,],[23,32,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','teamname.py',24),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','teamname.py',29),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','teamname.py',30),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','teamname.py',31),
  ('skiptag -> OPENSUP skiptag','skiptag',2,'p_skiptag','teamname.py',32),
  ('skiptag -> CLOSESUP skiptag','skiptag',2,'p_skiptag','teamname.py',33),
  ('skiptag -> <empty>','skiptag',0,'p_skiptag','teamname.py',34),
  ('handleli -> OPENLI OPENHREF CONTENT CLOSEHREF skiptag CLOSELI skiptag handleli','handleli',8,'p_handleli','teamname.py',37),
  ('handleli -> OPENLI CONTENT CLOSELI handleli','handleli',4,'p_handleli','teamname.py',38),
  ('handleli -> <empty>','handleli',0,'p_handleli','teamname.py',39),
  ('handleData -> OPENDATA skiptag handleli CLOSEDATA handleData','handleData',5,'p_handleData','teamname.py',46),
  ('handleData -> <empty>','handleData',0,'p_handleData','teamname.py',47),
  ('handlerow -> OPENROW handleData CLOSEROW','handlerow',3,'p_handlerow','teamname.py',50),
  ('table -> BEGINTEAMNAME skiptag OPENTABLE handlerow CLOSETABLE','table',5,'p_table','teamname.py',54),
]
